del /s *.bak
javac .\phase\*.java
javac .\_weekDo_\*.java
javac .\_公開資訊觀測站_\*.java
javac .\_算卷商比_\*.java
javac .\_算選擇權_\*.java
javac .\三大法人\*.java
javac .\抓凱基\*.java
javac .\抓卷商\*.java
javac .\抓成交明細\*.java
javac .\抓最佳五檔\*.java
javac .\抓證交所三大法人買賣超\*.java
javac .\抓證交所三大法人買賣超\all\*.java
javac .\抓證交所日成交資料\*.java
javac .\抓證交所每分資料\*.java
javac .\抓證交所每分資料\all\*.java
javac .\抓證交所融資卷\*.java
javac .\抓資本額\*.java
javac .\期指留倉\*.java
javac .\當日最大買超除成交量\*.java
javac .\算法人散戶分佈\*.java
javac .\計算凱基\*.java
javac .\計算卷商買賣金額\*.java
javac .\計算大盤資訊\*.java
javac .\計算成交明細\*.java
javac .\計算最佳五檔\*.java
javac .\計算算卷商資訊\*.java
javac .\計算證交所每分資料\*.java
javac .\計算證交所買賣超金額\*.java
javac .\證交所買賣超\*.java
javac .\選擇權\*.java
