var cookie=new CookieProcessor;cookie.setExpires(0);I18N||alert("Cannot initialize i18n script base.");var i18n=new I18N(cookie.getCookieByKey("lang"));String.prototype.format=function(){var a=arguments;return this.replace(/\{(\d+)\}/g,function(e,h){return a[h]})};Array.prototype.contains=function(a){for(var e=0;e<this.length;e++)if(this[e]==a)return true;return false};
var UTF8={encode:function(a){for(var e,h=-1,m=(a=a.split("")).length,k=String.fromCharCode;++h<m;a[h]=(e=a[h].charCodeAt(0))>=127?k(192|e>>>6)+k(128|e&63):a[h]);return a.join("")},decode:function(a){for(var e,h,m=-1,k=(a=a.split("")).length,j=String.fromCharCode;++m<k;(e=a[m].charCodeAt(0))&128&&(a[m]=(e&252)==192&&((h=a[m+1].charCodeAt(0))&192)==128?j(((e&3)<<6)+(h&63)):j(128),a[++m]=""));return a.join("")}};
function initLayout(){insertMenu("menu");insertSideBar("sidebar");insertFooter("footer");var a=i18n.getText("WEB_TITLE");$("#logo").html("<h1>{0}</h1><h2>Market Information System</h2>".format(a));$("#topmenu").html("<a href='#' id='langCht'></a><a href='#' id='langEng'></a>");$("#langCht").linkbutton({text:i18n.getText("TRADITIONAL_CHINESE")}).click(function(){i18n=new I18N("zh-tw");cookie.setCookie("lang","zh-tw");location.reload()});$("#langEng").linkbutton({text:i18n.getText("ENGLISH")}).click(function(){i18n=
new I18N("en-us");cookie.setCookie("lang","en-us");location.reload()});$("#sidebar").attr({icon:"icon-help"}).window({title:i18n.getText("ANNOUNCEMENT"),top:50,left:$(window).width()-180,collapsible:true,minimizable:false,maximizable:false,resizable:false,shadow:true,modal:false});$("input[type='text']").click(function(){this.select()})}
function insertMenu(a){insertPage("/menu.html",a);$("#menu_1_title").html(i18n.getText("MENU_1_TITLE"));$("#menu_1_item_01").html(i18n.getText("MENU_1_ITEM_01"));$("#menu_1_item_02").html(i18n.getText("MENU_1_ITEM_02"));$("#menu_1_item_03").html(i18n.getText("MENU_1_ITEM_03"));$("#menu_1_item_04").html(i18n.getText("MENU_1_ITEM_04"));$("#menu_2_title").html(i18n.getText("MENU_2_TITLE"));$("#menu_2_item_01").html(i18n.getText("MENU_2_ITEM_01"));$("#menu_3_title").html(i18n.getText("MENU_3_TITLE"));
$("#menu_3_item_01").html(i18n.getText("MENU_3_ITEM_01"));$("#menu_4_title").html(i18n.getText("MENU_4_TITLE"));$("#menu_4_subtitle_01").html(i18n.getText("MENU_4_SUBTITLE_01"));$("#menu_4_subitem_01_01").html(i18n.getText("MENU_4_SUBITEM_01_01"));$("#menu_4_subitem_01_02").html(i18n.getText("MENU_4_SUBITEM_01_02"));$("#menu_4_subtitle_02").html(i18n.getText("MENU_4_SUBTITLE_02"));$("#menu_4_subitem_02_01").html(i18n.getText("MENU_4_SUBITEM_02_01"));$("#menu_4_subitem_02_02").html(i18n.getText("MENU_4_SUBITEM_02_02"));
$("#menu_4_subtitle_03").html(i18n.getText("MENU_4_SUBTITLE_03"));$("#menu_4_subitem_03_01").html(i18n.getText("MENU_4_SUBITEM_03_01"));$("#menu_4_subitem_03_02").html(i18n.getText("MENU_4_SUBITEM_03_02"));$("#menu_4_subtitle_04").html(i18n.getText("MENU_4_SUBTITLE_04"));$("#menu_4_subitem_04_01").html(i18n.getText("MENU_4_SUBITEM_04_01"));$("#menu_4_subitem_04_02").html(i18n.getText("MENU_4_SUBITEM_04_02"));$("#menu_5_title").html(i18n.getText("MENU_5_TITLE"));$("#menu_5_subtitle_01").html(i18n.getText("MENU_5_SUBTITLE_01"));
$("#menu_5_subtitle_02").html(i18n.getText("MENU_5_SUBTITLE_02"));$(".menu_5_item_01").html(i18n.getText("MENU_5_ITEM_01"));$(".menu_5_item_02").html(i18n.getText("MENU_5_ITEM_02"));$(".menu_5_item_03").html(i18n.getText("MENU_5_ITEM_03"));$(".menu_5_item_04").html(i18n.getText("MENU_5_ITEM_04"));$(".menu_5_item_05").html(i18n.getText("MENU_5_ITEM_05"));$("#menu_6_subtitle_01").html(i18n.getText("MENU_6_SUBTITLE_01"));$("#menu_6_item_01").html(i18n.getText("MENU_6_ITEM_01"));$("#menu_7_title").html(i18n.getText("MENU_7_TITLE"));
$("#menu_7_item_01").html(i18n.getText("MENU_7_ITEM_01"));$("#menu_7_item_02").html(i18n.getText("MENU_7_ITEM_02"));$("#menu_7_item_03").html(i18n.getText("MENU_7_ITEM_03"));$("#menu_8_title").html(i18n.getText("MENU_8_TITLE"));$("#menu_8_item_01").html(i18n.getText("MENU_8_ITEM_01"));$("#menu_9_title").html(i18n.getText("MENU_9_TITLE"));$("#menu_9_item_01").html(i18n.getText("MENU_9_ITEM_01"));$("#menu_9_item_02").html(i18n.getText("MENU_9_ITEM_02"));$("#menu_9_item_03").html(i18n.getText("MENU_9_ITEM_03"));
$("#menu_9_item_04").html(i18n.getText("MENU_9_ITEM_04"));for(a=0;a<9;a++){var e=a+1;$("#mb_"+e).menubutton({menu:"#menu_"+e})}}function insertSideBar(a){insertPage("/sidebar.html",a);$("#sidebar_01").html(i18n.getText("SIDEBAR_01"));$("#sidebar_02").html(i18n.getText("SIDEBAR_02"))}function insertFooter(a){insertPage("/footer.html",a);$("#footer_01").html(i18n.getText("FOOTER_01"));$("#footer_02").html(i18n.getText("FOOTER_02"))}function insertPage(a,e){var h=readFile(a);$("#"+e).html(h)}
function readFile(a){a=a.indexOf(".csv")>0?a+"?sid="+(new Date).getTime():a;a=$.ajax({async:false,url:a,success:function(){}});return a.readyState==4||a.status==200?a.responseText:""}function getURLParam(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return a==null?"":a[1]}function isStockIdFormatValid(a){return a.length>=4&&a.length<=6&&a.indexOf("<")<0?true:false}
function Map(){this.keyArray=[];this.valArray=[];this.put=function(a,e){var h=this.findIt(a);if(h==-1){this.keyArray.push(a);this.valArray.push(e)}else this.valArray[h]=e};this.get=function(a){var e=null;a=this.findIt(a);if(a!=-1)e=this.valArray[a];return e};this.size=function(){return this.keyArray.length};this.clear=function(){for(var a=0;a<this.keyArray.length;a++){this.keyArray.pop();this.valArray.pop()}};this.keySet=function(){return this.keyArray};this.valSet=function(){return this.valArray};
this.showMe=function(){for(var a="",e=0;e<this.keyArray.length;e++)a+="Key: "+this.keyArray[e]+"\tValues: "+this.valArray[e]+"\n";return a};this.findIt=function(a){for(var e=-1,h=0;h<this.keyArray.length;h++)if(this.keyArray[h]==a){e=h;break}return e};this.remove=function(a){a=this.findIt(a);if(a!=-1){this.keyArray=this.keyArray.removeAt(a);this.valArray=this.valArray.removeAt(a)}}}function removeAt(a){var e=this.slice(0,a);a=this.slice(a+1);return e.concat(a)}Array.prototype.removeAt=removeAt;
var LoadingTag={id:"loadingTag",message:i18n.getText("LOADING_TEXT"),show:function(){var a=document.createElement("div");a.id=LoadingTag.id;a.appendChild(document.createTextNode(LoadingTag.message));document.getElementsByTagName("body")[0].appendChild(a)},hide:function(){$("#loadingTag").remove()}},mapETF=new Map;mapETF.put("0050",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});
mapETF.put("0051",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});mapETF.put("0052",{cht:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert.aspx",eng:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert_en.aspx"});mapETF.put("0053",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});mapETF.put("0054",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});
mapETF.put("0055",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});mapETF.put("0056",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});mapETF.put("0057",{cht:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert.aspx",eng:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert_en.aspx"});mapETF.put("0058",{cht:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert.aspx",eng:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert_en.aspx"});
mapETF.put("0059",{cht:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert.aspx",eng:"http:
//www.fubonetf.com/etf/realtime_fund_nav_advert_en.aspx"});mapETF.put("0060",{cht:"http:
//www.p-shares.com/_big5_index/nw.asp",eng:"http:
//www.p-shares.com/_big5_index/english/eadvert.asp"});mapETF.put("0061",{cht:"http:
//www.p-shares.com/_big5_index/petf1inter.asp",eng:"http:
//www.p-shares.com/_big5_index/petf1inter.asp"});
mapETF.put("0080",{cht:"http:
//www.assetmanagement.hsbc.com.tw/etf/etf_message.asp?ETFOK=N",eng:"http:
//www.assetmanagement.hsbc.com.tw/etf/etf_message.asp?ETFOK=N"});mapETF.put("0081",{cht:"http:
//www.assetmanagement.hsbc.com.tw/etf/etf_message.asp?ETFOK=N",eng:"http:
//www.assetmanagement.hsbc.com.tw/etf/etf_message.asp?ETFOK=N"});var largeTWSE=i18n.getText("MARKET_DESCRIPTION_TWSE"),largeOTC=i18n.getText("MARKET_DESCRIPTION_OTC"),mapLarge=new Map;
mapLarge.put("TL31",{title:i18n.getText("LARGE_NON_PAIRED_SINGLE").format(largeTWSE),cht:"L31.html",eng:"L31en.html"});mapLarge.put("TL63",{title:i18n.getText("LARGE_PAIRED_SINGLE").format(largeTWSE),cht:"L63.html",eng:"L63en.html"});mapLarge.put("TL33",{title:i18n.getText("LARGE_NON_PAIRED_BASKET").format(largeTWSE),cht:"L33.html",eng:"L33en.html"});mapLarge.put("TL65",{title:i18n.getText("LARGE_PAIRED_BASKET").format(largeTWSE),cht:"L65.html",eng:"L65en.html"});
mapLarge.put("TL500",{title:i18n.getText("LARGE_PRICE_LIMIT").format(largeTWSE),cht:"L500.html",eng:"L500en.html"});mapLarge.put("OL31",{title:i18n.getText("LARGE_NON_PAIRED_SINGLE").format(largeOTC),cht:"OTCL31.html",eng:"OTCL31en.html"});mapLarge.put("OL63",{title:i18n.getText("LARGE_PAIRED_SINGLE").format(largeOTC),cht:"OTCL63.html",eng:"OTCL63en.html"});mapLarge.put("OL33",{title:i18n.getText("LARGE_NON_PAIRED_BASKET").format(largeOTC),cht:"OTCL33.html",eng:"OTCL33en.html"});
mapLarge.put("OL65",{title:i18n.getText("LARGE_PAIRED_BASKET").format(largeOTC),cht:"OTCL65.html",eng:"OTCL65en.html"});mapLarge.put("OL500",{title:i18n.getText("LARGE_PRICE_LIMIT").format(largeOTC),cht:"OTCL500.html",eng:"OTCL500en.html"});
function CookieProcessor(){var a=0,e=0,h=[],m=document.cookie;(function(){var k=m.split(";");a=m.length>0?k.length:0;for(var j=0;j<a;j++)h[j]=$.trim(k[j]).split("=")})();this.getArray=function(){return h};this.getString=function(){return m.trim()};this.getCookieByKey=function(k){for(var j=0;j<a;j++)if(h[j][0]==$.trim(k))return h[j][1];return""};this.setCookie=function(k,j){document.cookie=k+"="+j};this.setExpires=function(k){e=(new Date).getTime()+k;document.cookie="; expires="+(new Date(e)).toGMTString()}}
function GridRender(a,e){var h=a,m=e,k=1,j=null,q=document.createDocumentFragment(),o=null,s=null,p=null;this.getCurrentPage=function(){return k};this.getTHead=function(){if(!o){o=document.createElement("thead");o.style.height="0px"}return o};this.getTBody=function(){return!s?s=document.createElement("tbody"):s};this.getTFoot=function(){if(!p){p=document.createElement("tfoot");p.style.height="0px"}return p};this.setLayout=function(c){m=c};this.clear=function(){for(var c=h.rows.length;c>0;c--)h.deleteRow(c-
1);if(o){var b=o.childNodes;for(c=b.length-1;c>=0;c--)o.removeChild(b[c])}if(p){b=p.childNodes;for(c=b.length-1;c>=0;c--)p.removeChild(b[c])}};this.draw=function(){q.appendChild(this.getTHead());q.appendChild(this.getTBody());q.appendChild(this.getTFoot());h.appendChild(q);$("tbody tr:nth-child(odd)").addClass("odd")};this.insertMarketIndexes=function(c,b){b&&this.insertTitleRow(false);for(var d=AppConfig.getIndexList(c[0].market).keySet(),g=0;g<d.length;g++){for(var f=null,i=0;i<c.length;i++)if(d[g]==
c[i].id){f=c[i];break}f!=null&&this.insertRow(f,false)}this.draw()};this.insertTradesData=function(c){for(var b=0;b<c.length;b++){var d=c[b];this.insertRow(d,false);if(d.id==201)this.insertRow({id:d.id,name:i18n.getLanguage().substr(0,2)=="zh"?d.name.replace(i18n.getText("QUANTITY"),i18n.getText("RECORDS")):"Transaction",time:d.time,latestPrice:d.change,change:d.latestPrice,direction:d.direction,market:d.market},false)}this.draw()};this.insertOrdersData=function(c){for(var b=0;b<c.length;b++){var d=
c[b];this.insertRow(d,false);this.insertRow({id:d.id,name:i18n.getLanguage().substr(0,2)=="zh"?d.name.replace(i18n.getText("QUANTITY"),i18n.getText("RECORDS")):"Orders",time:d.time,latestPrice:d.change,change:d.latestPrice,direction:d.direction,market:d.market},false)}this.draw()};this.render=function(c,b){LoadingTag.show();this.clear();if(b==null)b=1;k=b;j=c;this.insertTitleRow();j.length==0&&this.insertNoStockRow();var d=j.length>AppConfig.pageSize?AppConfig.pageSize:j.length,g=Math.ceil(j.length/
AppConfig.pageSize);if(g<1)g=1;for(var f=0;f<d;f++){var i=j[f+(b-1)*AppConfig.pageSize];i?this.insertRow(AppConfig.getStockInfo(i)):this.insertBlankRow()}this.insertPagingBar(j.length,b);this.insertCommentRow(commentList);this.draw();var l=this;$("#pagination").html(i18n.getText("GRID_PAGINATION").format(b,g));$("#btnFirst").click(function(){l.changePage(1)});$("#btnPrev").click(function(){l.changePage(b-1)});$("#btnNext").click(function(){l.changePage(b+1)});$("#btnLast").click(function(){l.changePage(g)});
$("#txtPage").addClass("pageNo").numberbox({min:1,max:g}).validatebox({required:true,validType:"length[1, 9999]",missingMessage:i18n.getText("REQUIRED_TEXT")}).keypress(function(n){n.keyCode==13&&l.changePage(this.value);if(n.shiftKey&&n.keyCode==45||n.which!=8&&n.which!=0&&(n.which<48||n.which>57))return false}).click(function(){this.select()});$("#cmbPageSize").change(function(){if(!(this.value>=50&&!confirm(i18n.getText("GRID_HUGE_AMOUNT_WARNING"))))AppConfig.pageSize=this.value;l.changePage(1)});
LoadingTag.hide()};this.insertRow=function(c,b){var d=this.getTBody(),g=document.createElement("tr");if(b==null||b){var f=document.createElement("td");f.className="idNumber";f.innerHTML=d.childNodes.length+1;g.appendChild(f)}for(f=0;f<m.length;f++){var i=m[f],l=document.createElement("td");switch(i.format){case "BLANK":l.innerHTML="&nbsp;";break;case "SYMBOL":l.style.textAlign="center";break;case "NUMERIC":l.style.textAlign="right";break;case "TEXT":l.style.textAlign="left";break;default:l.style.textAlign=
"center";break}if(i.url){var n=i.url.displayText,t=i.url.target,r;if(n){r=i.url.link;i="<a href='{0}' target='{1}'>{2}</a>".format(r,t,n)}else{r=i.url.link.format(c[i.url.key]);i="<a href='{0}' target='{1}'>{2}</a>".format(r,t,c[i.property])}l.innerHTML=i}else l.innerHTML=i.property?c[i.property]:"&nbsp;";g.appendChild(l)}d.appendChild(g)};this.insertTitleRow=function(c){var b=this.getTHead(),d=document.createElement("tr");if(c==null||c){c=document.createElement("th");c.innerHTML="#";d.appendChild(c)}for(c=
0;c<m.length;c++){var g=m[c],f=document.createElement("th");f.innerHTML=g.title;d.appendChild(f)}b.appendChild(d)};this.insertBlankRow=function(c){if(c==null)c=this.getTBody();var b=document.createElement("tr"),d=document.createElement("td");d.colSpan=99;d.className="";d.innerHTML="&nbsp;";b.appendChild(d);c.appendChild(b)};this.insertNoStockRow=function(c){if(c==null)c=this.getTBody();var b=document.createElement("tr"),d=document.createElement("td");d.colSpan=99;d.className="noData";d.innerHTML=
i18n.getText("GRID_NO_STOCK");b.appendChild(d);c.appendChild(b)};this.insertCommentRow=function(c,b){if(b==null)b=this.getTFoot();for(var d=["<ol>"],g=0;g<c.length;g++)d.push("<li>{0}</li>".format(c[g]));d.push("</ol>");g=document.createElement("tr");var f=document.createElement("td");f.colSpan=99;f.className="commentBar";f.innerHTML=d.join(" ");g.appendChild(f);b.appendChild(g)};this.insertPagingBar=function(c,b,d){if(d==null)d=this.getTFoot();var g=Math.ceil(c/AppConfig.pageSize);if(g<1)g=1;var f=
b!=1,i=f&&b<=g,l=b<g;g=l&&b!=g;b=["<span style='float: left; width: 50%; text-align: left;'>"];if(f){b.push("<a id='btnFirst' href='#'>");b.push("<img src='/image/page-first.gif' width='32' height='16' title='{0}' /></a>".format(i18n.getText("GRID_FIRST_PAGE")))}else b.push("<img src='/image/page-first-disabled.gif' width='32' height='16' />");if(i){b.push("<a id='btnPrev' href='#'>");b.push("<img src='/image/page-prev.gif' width='32' height='16' title='{0}' /></a>".format(i18n.getText("GRID_PREV_PAGE")))}else b.push("<img src='/image/page-prev-disabled.gif' width='32' height='16' />");
b.push("<span class='seperator'>&nbsp;|&nbsp;</span>");b.push("<span id='pagination'></span>");b.push("<span class='seperator'>&nbsp;|&nbsp;</span>");if(l){b.push("<a id='btnNext' href='#'>");b.push("<img src='/image/page-next.gif' title='{0}' width='32' height='16' /></a>".format(i18n.getText("GRID_NEXT_PAGE")))}else b.push("<img src='/image/page-next-disabled.gif' width='32' height='16' />");if(g){b.push("<a id='btnLast' href='#'>");b.push("<img src='/image/page-last.gif' title='{0}' width='32' height='16' /></a>".format(i18n.getText("GRID_LAST_PAGE")))}else b.push("<img src='/image/page-last-disabled.gif' width='32' height='16' />");
b.push("</span>");b.push("<span style='float: right; width: 50%; text-align: right; font-weight: bold;'>");b.push("<span>{0}".format(i18n.getText("GRID_PAGE_SIZE")));b.push("<select id='cmbPageSize'>");for(f=0;f<AppConfig.gridPageSize.length;f++){i=AppConfig.gridPageSize[f];l=i==AppConfig.pageSize?"selected='true'":"";g=i>999?i18n.getText("GRID_PAGE_SIZE_ALL"):i;b.push("<option value='{0}' {1}>{2}</option>".format(i,l,g))}b.push("</select></span> | ");b.push(i18n.getText("GRID_PAGING_TOTAL_RECORDS")+
c+"</span>");c=document.createElement("tr");f=document.createElement("td");f.className="paginationBar";f.colSpan=99;f.innerHTML=b.join(" ");c.appendChild(f);d.appendChild(c)};this.changePage=function(c){var b=document.getElementById("txtPage");if(b)if(!c||isNaN(c)){alert(i18n.getText("ENTER_VALID_PAGE"));b.value=k}else{var d=Math.ceil(j.length/AppConfig.pageSize);if(d<1)d=1;if(c>d){alert(i18n.getText("INVALID_PAGE_EXCEED").format(d));b.value=k;b.select()}else{k=parseInt(c);this.render(j,k)}}}};